### ISSUE TITLE
the single image test result is worse than expected

### ISSUE THREAD

**Issue by lfxx** [koyeongmin/PINet#2]
i use the test.py to test single image,get the result below:
![result](https://user-images.githubusercontent.com/27956643/74934561-73b33600-5421-11ea-95f6-b3ed78cb3ac2.png)
what's wrong?@koyeongmin

**Comment by lfxx** [comment]
![result1](https://user-images.githubusercontent.com/27956643/74939429-d230e200-542a-11ea-8761-3e934ba01a21.png)


this one is also not good

**Comment by koyeongmin** [comment]
Our provided model was trained on tuSimple dataset without extra data.
Your test images look different from tuSimple dataset.
Because tuSimple data consist only around 3000 images, our model cannot cover various scenes.
If you have your custom training set, I recommend to train again on your dataset.

**Comment by lfxx** [comment]
> Our provided model was trained on tuSimple dataset without extra data.
> Your test images look different from tuSimple dataset.
> Because tuSimple data consist only around 3000 images, our model cannot cover various scenes.
> If you have your custom training set, I recommend to train again on your dataset.

thanks for your kindly reply,i will try it:)
